# Generated by Django 4.2 on 2023-07-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('ingredientes', models.CharField(max_length=500, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('imgn_ref', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRev', models.DateField(null=True)),
                ('nHab', models.IntegerField()),
                ('totaliniRev', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('totalfinRev', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreS', models.CharField(max_length=200, null=True)),
                ('descripcionS', models.CharField(max_length=1000, null=True)),
                ('precioS', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreu', models.CharField(max_length=200, null=True)),
                ('tipoU', models.CharField(max_length=200, null=True)),
                ('rut', models.CharField(max_length=200, null=True)),
                ('fNac', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contrasenia', models.CharField(max_length=200, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
